# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_flow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(236, 243, 251);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(6, 10, 6, 10)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_up = QtWidgets.QFrame(Dialog)
        self.frame_up.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_up.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_up.setObjectName("frame_up")
        self.horizontalLayout_up = QtWidgets.QHBoxLayout(self.frame_up)
        self.horizontalLayout_up.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_up.setSpacing(6)
        self.horizontalLayout_up.setObjectName("horizontalLayout_up")
        self.frame_left = QtWidgets.QFrame(self.frame_up)
        self.frame_left.setMinimumSize(QtCore.QSize(414, 0))
        self.frame_left.setMaximumSize(QtCore.QSize(414, 16777215))
        self.frame_left.setStyleSheet("#frame_left{\n"
"    background: #FFFFFF;\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: 1px solid #DBDBDB;\n"
"}")
        self.frame_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left.setObjectName("frame_left")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_left)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_title = QtWidgets.QFrame(self.frame_left)
        self.frame_title.setStyleSheet("#frame_title{\n"
"    background: #FFFFFF;\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: none;\n"
"}")
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout_title_2 = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout_title_2.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_title_2.setObjectName("horizontalLayout_title_2")
        self.label = QtWidgets.QLabel(self.frame_title)
        self.label.setMaximumSize(QtCore.QSize(56, 42))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/image_title.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_title_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_title_2.addItem(spacerItem)
        self.pushButton_00 = QtWidgets.QPushButton(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.pushButton_00.setFont(font)
        self.pushButton_00.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icon_about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_00.setIcon(icon1)
        self.pushButton_00.setObjectName("pushButton_00")
        self.horizontalLayout_title_2.addWidget(self.pushButton_00)
        self.verticalLayout_7.addWidget(self.frame_title)
        self.tabWidget = QtWidgets.QTabWidget(self.frame_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget{\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QTabBar::tab {\n"
"    background: #00337E;\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid #00337E;\n"
"    border-bottom: 2px solid rgb(255, 255, 255);\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    padding: 4px 20px;\n"
"    margin-right: 2px; \n"
"    font-size: 12px; \n"
"}\n"
"QTabBar::tab:selected {\n"
"    background: rgb(255, 255, 255);\n"
"    color: #00337E;\n"
"    border-bottom: none;\n"
"    font-weight: bold;\n"
"}\n"
"QTabBar::tab:hover:!selected {\n"
"    background: rgb(0, 83, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_1.sizePolicy().hasHeightForWidth())
        self.tab_1.setSizePolicy(sizePolicy)
        self.tab_1.setStyleSheet("")
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_tab_1 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_tab_1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_tab_1.setSpacing(0)
        self.verticalLayout_tab_1.setObjectName("verticalLayout_tab_1")
        self.scrollArea_1 = QtWidgets.QScrollArea(self.tab_1)
        self.scrollArea_1.setStyleSheet("QScrollArea{\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.scrollArea_1.setWidgetResizable(True)
        self.scrollArea_1.setObjectName("scrollArea_1")
        self.scrollAreaWidgetContents_1 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_1.setGeometry(QtCore.QRect(0, 0, 390, 445))
        self.scrollAreaWidgetContents_1.setObjectName("scrollAreaWidgetContents_1")
        self.verticalLayout_scroll_1 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_1)
        self.verticalLayout_scroll_1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_scroll_1.setSpacing(0)
        self.verticalLayout_scroll_1.setObjectName("verticalLayout_scroll_1")
        self.frame_left_11 = QtWidgets.QFrame(self.scrollAreaWidgetContents_1)
        self.frame_left_11.setMinimumSize(QtCore.QSize(390, 130))
        self.frame_left_11.setMaximumSize(QtCore.QSize(390, 130))
        self.frame_left_11.setStyleSheet("#frame_left_11{\n"
"    background: #FFFFFF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"QFrame{\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_left_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_11.setObjectName("frame_left_11")
        self.verticalLayout_left_11 = QtWidgets.QVBoxLayout(self.frame_left_11)
        self.verticalLayout_left_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_left_11.setSpacing(0)
        self.verticalLayout_left_11.setObjectName("verticalLayout_left_11")
        self.frame_left_110 = QtWidgets.QFrame(self.frame_left_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_left_110.sizePolicy().hasHeightForWidth())
        self.frame_left_110.setSizePolicy(sizePolicy)
        self.frame_left_110.setMinimumSize(QtCore.QSize(0, 24))
        self.frame_left_110.setMaximumSize(QtCore.QSize(16777215, 24))
        self.frame_left_110.setStyleSheet("#frame_left_110{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"#frame_110{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}\n"
"QLabel{\n"
"    font-weight: 400;\n"
"    font-size: 12px;\n"
"    color: #303133;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"    background-color: rgb(140, 190, 239);\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(140, 190, 239);\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_left_110.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_110.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_110.setObjectName("frame_left_110")
        self.horizontalLayout_left_110 = QtWidgets.QHBoxLayout(self.frame_left_110)
        self.horizontalLayout_left_110.setContentsMargins(6, 0, 10, 0)
        self.horizontalLayout_left_110.setSpacing(6)
        self.horizontalLayout_left_110.setObjectName("horizontalLayout_left_110")
        self.frame_110 = QtWidgets.QFrame(self.frame_left_110)
        self.frame_110.setStyleSheet("")
        self.frame_110.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_110.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_110.setObjectName("frame_110")
        self.horizontalLayout_110 = QtWidgets.QHBoxLayout(self.frame_110)
        self.horizontalLayout_110.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_110.setSpacing(6)
        self.horizontalLayout_110.setObjectName("horizontalLayout_110")
        self.label_1101 = QtWidgets.QLabel(self.frame_110)
        self.label_1101.setMinimumSize(QtCore.QSize(15, 15))
        self.label_1101.setMaximumSize(QtCore.QSize(15, 15))
        self.label_1101.setText("")
        self.label_1101.setPixmap(QtGui.QPixmap(":/icons/icon_01.png"))
        self.label_1101.setScaledContents(True)
        self.label_1101.setObjectName("label_1101")
        self.horizontalLayout_110.addWidget(self.label_1101)
        self.label_1102 = QtWidgets.QLabel(self.frame_110)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_1102.setFont(font)
        self.label_1102.setObjectName("label_1102")
        self.horizontalLayout_110.addWidget(self.label_1102)
        self.horizontalLayout_left_110.addWidget(self.frame_110)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_left_110.addItem(spacerItem1)
        self.pushButton_110 = QtWidgets.QPushButton(self.frame_left_110)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.pushButton_110.setFont(font)
        self.pushButton_110.setText("")
        self.pushButton_110.setIcon(icon1)
        self.pushButton_110.setObjectName("pushButton_110")
        self.horizontalLayout_left_110.addWidget(self.pushButton_110)
        self.verticalLayout_left_11.addWidget(self.frame_left_110)
        self.frame_left_111 = QtWidgets.QFrame(self.frame_left_11)
        self.frame_left_111.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_left_111.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_left_111.setStyleSheet("QLabel{\n"
"    font-weight: 400;\n"
"    font-size: 12px;\n"
"    color: #303133;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}\n"
"QPushButton {\n"
"    height: 20px;\n"
"    background: #00337E;\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgb(0, 83, 200);\n"
"}\n"
"QComboBox{\n"
"    background: radial-gradient( #ECECED 0%, #FFFFFF 100%);\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    border: 1px solid #DBDBDD;\n"
"}")
        self.frame_left_111.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_111.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_111.setObjectName("frame_left_111")
        self.horizontalLayout_left_111 = QtWidgets.QHBoxLayout(self.frame_left_111)
        self.horizontalLayout_left_111.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_left_111.setObjectName("horizontalLayout_left_111")
        self.label_1111 = QtWidgets.QLabel(self.frame_left_111)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_1111.setFont(font)
        self.label_1111.setObjectName("label_1111")
        self.horizontalLayout_left_111.addWidget(self.label_1111)
        self.label_1112 = QtWidgets.QLabel(self.frame_left_111)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_1112.setFont(font)
        self.label_1112.setObjectName("label_1112")
        self.horizontalLayout_left_111.addWidget(self.label_1112)
        self.comboBox_111 = QtWidgets.QComboBox(self.frame_left_111)
        self.comboBox_111.setMinimumSize(QtCore.QSize(60, 24))
        self.comboBox_111.setMaximumSize(QtCore.QSize(60, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_111.setFont(font)
        self.comboBox_111.setObjectName("comboBox_111")
        self.comboBox_111.addItem("")
        self.comboBox_111.addItem("")
        self.horizontalLayout_left_111.addWidget(self.comboBox_111)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_left_111.addItem(spacerItem2)
        self.pushButton_111 = QtWidgets.QPushButton(self.frame_left_111)
        self.pushButton_111.setMinimumSize(QtCore.QSize(108, 20))
        self.pushButton_111.setMaximumSize(QtCore.QSize(108, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_111.setFont(font)
        self.pushButton_111.setStyleSheet("")
        self.pushButton_111.setObjectName("pushButton_111")
        self.horizontalLayout_left_111.addWidget(self.pushButton_111)
        self.verticalLayout_left_11.addWidget(self.frame_left_111)
        self.frame_left_112 = QtWidgets.QFrame(self.frame_left_11)
        self.frame_left_112.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_left_112.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_left_112.setStyleSheet("QPushButton{\n"
"    width: 60px;\n"
"    height: 20px;\n"
"    background: qradialgradient(cx:0%, cy:0%, radius:100%, fx:50%, fy:50%, stop:0 #ECECED, stop:1 #FFFFFF);\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    border: 1px solid #DBDBDD;\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgb(226, 226, 227);\n"
"}\n"
"QLineEdit{\n"
"    width: 309px;\n"
"    height: 20px;\n"
"    background: #ECF3FB;\n"
"    border-radius: 2px 2px 2px 2px;\n"
"    border: 1px solid #DBDBDB;\n"
"}")
        self.frame_left_112.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_112.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_112.setObjectName("frame_left_112")
        self.horizontalLayout_left_112 = QtWidgets.QHBoxLayout(self.frame_left_112)
        self.horizontalLayout_left_112.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_left_112.setSpacing(6)
        self.horizontalLayout_left_112.setObjectName("horizontalLayout_left_112")
        self.lineEdit_112 = QtWidgets.QLineEdit(self.frame_left_112)
        self.lineEdit_112.setObjectName("lineEdit_112")
        self.horizontalLayout_left_112.addWidget(self.lineEdit_112)
        self.pushButton_112 = QtWidgets.QPushButton(self.frame_left_112)
        self.pushButton_112.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_112.setFont(font)
        self.pushButton_112.setObjectName("pushButton_112")
        self.horizontalLayout_left_112.addWidget(self.pushButton_112)
        self.verticalLayout_left_11.addWidget(self.frame_left_112)
        self.frame_left_113 = QtWidgets.QFrame(self.frame_left_11)
        self.frame_left_113.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_left_113.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_left_113.setStyleSheet("QRadioButton{\n"
"    border: none;\n"
"    background: radial-gradient( #ECECED 0%, #FFFFFF 100%);\n"
"    border-radius: 4px 4px 4px 4px;\n"
"}")
        self.frame_left_113.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_113.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_113.setObjectName("frame_left_113")
        self.horizontalLayout_left_113 = QtWidgets.QHBoxLayout(self.frame_left_113)
        self.horizontalLayout_left_113.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_left_113.setObjectName("horizontalLayout_left_113")
        self.radioButton_113 = QtWidgets.QRadioButton(self.frame_left_113)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        self.radioButton_113.setFont(font)
        self.radioButton_113.setStyleSheet("")
        self.radioButton_113.setObjectName("radioButton_113")
        self.horizontalLayout_left_113.addWidget(self.radioButton_113)
        self.verticalLayout_left_11.addWidget(self.frame_left_113)
        self.verticalLayout_scroll_1.addWidget(self.frame_left_11, 0, QtCore.Qt.AlignHCenter)
        self.frame_left_12 = QtWidgets.QFrame(self.scrollAreaWidgetContents_1)
        self.frame_left_12.setMinimumSize(QtCore.QSize(390, 160))
        self.frame_left_12.setMaximumSize(QtCore.QSize(390, 160))
        self.frame_left_12.setStyleSheet("#frame_left_12{\n"
"    background: #FFFFFF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"QFrame{\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_left_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_12.setObjectName("frame_left_12")
        self.verticalLayout_left_12 = QtWidgets.QVBoxLayout(self.frame_left_12)
        self.verticalLayout_left_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_left_12.setSpacing(0)
        self.verticalLayout_left_12.setObjectName("verticalLayout_left_12")
        self.frame_left_120 = QtWidgets.QFrame(self.frame_left_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_left_120.sizePolicy().hasHeightForWidth())
        self.frame_left_120.setSizePolicy(sizePolicy)
        self.frame_left_120.setMinimumSize(QtCore.QSize(0, 24))
        self.frame_left_120.setMaximumSize(QtCore.QSize(16777215, 24))
        self.frame_left_120.setStyleSheet("#frame_left_120{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"#frame_120{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}\n"
"QLabel{\n"
"    font-weight: 400;\n"
"    font-size: 12px;\n"
"    color: #303133;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"    background-color: rgb(140, 190, 239);\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(140, 190, 239);\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_left_120.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_120.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_120.setObjectName("frame_left_120")
        self.horizontalLayout_left_120 = QtWidgets.QHBoxLayout(self.frame_left_120)
        self.horizontalLayout_left_120.setContentsMargins(6, 0, 10, 0)
        self.horizontalLayout_left_120.setSpacing(6)
        self.horizontalLayout_left_120.setObjectName("horizontalLayout_left_120")
        self.frame_120 = QtWidgets.QFrame(self.frame_left_120)
        self.frame_120.setStyleSheet("")
        self.frame_120.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_120.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_120.setObjectName("frame_120")
        self.horizontalLayout_120 = QtWidgets.QHBoxLayout(self.frame_120)
        self.horizontalLayout_120.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_120.setSpacing(6)
        self.horizontalLayout_120.setObjectName("horizontalLayout_120")
        self.label_1201 = QtWidgets.QLabel(self.frame_120)
        self.label_1201.setMinimumSize(QtCore.QSize(15, 15))
        self.label_1201.setMaximumSize(QtCore.QSize(15, 15))
        self.label_1201.setText("")
        self.label_1201.setPixmap(QtGui.QPixmap(":/icons/icon_02.png"))
        self.label_1201.setScaledContents(True)
        self.label_1201.setObjectName("label_1201")
        self.horizontalLayout_120.addWidget(self.label_1201)
        self.label_1202 = QtWidgets.QLabel(self.frame_120)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_1202.setFont(font)
        self.label_1202.setObjectName("label_1202")
        self.horizontalLayout_120.addWidget(self.label_1202)
        self.horizontalLayout_left_120.addWidget(self.frame_120)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_left_120.addItem(spacerItem3)
        self.pushButton_120 = QtWidgets.QPushButton(self.frame_left_120)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.pushButton_120.setFont(font)
        self.pushButton_120.setText("")
        self.pushButton_120.setIcon(icon1)
        self.pushButton_120.setObjectName("pushButton_120")
        self.horizontalLayout_left_120.addWidget(self.pushButton_120)
        self.verticalLayout_left_12.addWidget(self.frame_left_120)
        self.frame_left_121 = QtWidgets.QFrame(self.frame_left_12)
        self.frame_left_121.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_left_121.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_left_121.setStyleSheet("QLabel{\n"
"    font-weight: 400;\n"
"    font-size: 12px;\n"
"    color: #303133;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}\n"
"QPushButton {\n"
"    height: 20px;\n"
"    background: #00337E;\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgb(0, 83, 200);\n"
"}\n"
"QRadioButton{\n"
"    border: none;\n"
"    background: radial-gradient( #ECECED 0%, #FFFFFF 100%);\n"
"    border-radius: 4px 4px 4px 4px;\n"
"}")
        self.frame_left_121.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_121.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_121.setObjectName("frame_left_121")
        self.horizontalLayout_left_121 = QtWidgets.QHBoxLayout(self.frame_left_121)
        self.horizontalLayout_left_121.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_left_121.setObjectName("horizontalLayout_left_121")
        self.label_121 = QtWidgets.QLabel(self.frame_left_121)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_121.setFont(font)
        self.label_121.setObjectName("label_121")
        self.horizontalLayout_left_121.addWidget(self.label_121)
        self.pushButton_121 = QtWidgets.QPushButton(self.frame_left_121)
        self.pushButton_121.setMinimumSize(QtCore.QSize(108, 20))
        self.pushButton_121.setMaximumSize(QtCore.QSize(108, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_121.setFont(font)
        self.pushButton_121.setStyleSheet("")
        self.pushButton_121.setObjectName("pushButton_121")
        self.horizontalLayout_left_121.addWidget(self.pushButton_121)
        self.verticalLayout_left_12.addWidget(self.frame_left_121)
        self.frame_left_122 = QtWidgets.QFrame(self.frame_left_12)
        self.frame_left_122.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_left_122.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_left_122.setStyleSheet("QPushButton{\n"
"    width: 60px;\n"
"    height: 20px;\n"
"    background: qradialgradient(cx:0%, cy:0%, radius:100%, fx:50%, fy:50%, stop:0 #ECECED, stop:1 #FFFFFF);\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    border: 1px solid #DBDBDD;\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgb(226, 226, 227);\n"
"}\n"
"QLineEdit{\n"
"    width: 309px;\n"
"    height: 20px;\n"
"    background: #ECF3FB;\n"
"    border-radius: 2px 2px 2px 2px;\n"
"    border: 1px solid #DBDBDB;\n"
"}")
        self.frame_left_122.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_122.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_122.setObjectName("frame_left_122")
        self.horizontalLayout_left_122 = QtWidgets.QHBoxLayout(self.frame_left_122)
        self.horizontalLayout_left_122.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_left_122.setSpacing(6)
        self.horizontalLayout_left_122.setObjectName("horizontalLayout_left_122")
        self.lineEdit_122 = QtWidgets.QLineEdit(self.frame_left_122)
        self.lineEdit_122.setObjectName("lineEdit_122")
        self.horizontalLayout_left_122.addWidget(self.lineEdit_122)
        self.pushButton_122 = QtWidgets.QPushButton(self.frame_left_122)
        self.pushButton_122.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_122.setFont(font)
        self.pushButton_122.setObjectName("pushButton_122")
        self.horizontalLayout_left_122.addWidget(self.pushButton_122)
        self.verticalLayout_left_12.addWidget(self.frame_left_122)
        self.frame_left_123 = QtWidgets.QFrame(self.frame_left_12)
        self.frame_left_123.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_left_123.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_left_123.setStyleSheet("QPushButton{\n"
"    width: 60px;\n"
"    height: 20px;\n"
"    background: qradialgradient(cx:0%, cy:0%, radius:100%, fx:50%, fy:50%, stop:0 #ECECED, stop:1 #FFFFFF);\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    border: 1px solid #DBDBDD;\n"
"}\n"
"QLabel{\n"
"    font-weight: 400;\n"
"    font-size: 12px;\n"
"    color: #303133;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}\n"
"QLineEdit{\n"
"    width: 120px;\n"
"    height: 20px;\n"
"    background: #ECF3FB;\n"
"    border-radius: 2px 2px 2px 2px;\n"
"    border: 1px solid #DBDBDB;\n"
"}")
        self.frame_left_123.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_123.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_123.setObjectName("frame_left_123")
        self.horizontalLayout_left_123 = QtWidgets.QHBoxLayout(self.frame_left_123)
        self.horizontalLayout_left_123.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_left_123.setObjectName("horizontalLayout_left_123")
        self.label_1231 = QtWidgets.QLabel(self.frame_left_123)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_1231.setFont(font)
        self.label_1231.setObjectName("label_1231")
        self.horizontalLayout_left_123.addWidget(self.label_1231)
        self.lineEdit_1231 = QtWidgets.QLineEdit(self.frame_left_123)
        self.lineEdit_1231.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_1231.setObjectName("lineEdit_1231")
        self.horizontalLayout_left_123.addWidget(self.lineEdit_1231)
        self.label_1232 = QtWidgets.QLabel(self.frame_left_123)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_1232.setFont(font)
        self.label_1232.setObjectName("label_1232")
        self.horizontalLayout_left_123.addWidget(self.label_1232)
        self.lineEdit_1232 = QtWidgets.QLineEdit(self.frame_left_123)
        self.lineEdit_1232.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_1232.setObjectName("lineEdit_1232")
        self.horizontalLayout_left_123.addWidget(self.lineEdit_1232)
        self.label_1233 = QtWidgets.QLabel(self.frame_left_123)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_1233.setFont(font)
        self.label_1233.setObjectName("label_1233")
        self.horizontalLayout_left_123.addWidget(self.label_1233)
        self.verticalLayout_left_12.addWidget(self.frame_left_123)
        self.frame_left_124 = QtWidgets.QFrame(self.frame_left_12)
        self.frame_left_124.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_left_124.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_left_124.setStyleSheet("QPushButton{\n"
"    width: 60px;\n"
"    height: 20px;\n"
"    background: qradialgradient(cx:0%, cy:0%, radius:100%, fx:50%, fy:50%, stop:0 #ECECED, stop:1 #FFFFFF);\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    border: 1px solid #DBDBDD;\n"
"}\n"
"QLabel{\n"
"    font-weight: 400;\n"
"    font-size: 12px;\n"
"    color: #303133;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}\n"
"QLineEdit{\n"
"    width: 120px;\n"
"    height: 20px;\n"
"    background: #ECF3FB;\n"
"    border-radius: 2px 2px 2px 2px;\n"
"    border: 1px solid #DBDBDB;\n"
"}")
        self.frame_left_124.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_124.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_124.setObjectName("frame_left_124")
        self.horizontalLayout_left_124 = QtWidgets.QHBoxLayout(self.frame_left_124)
        self.horizontalLayout_left_124.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_left_124.setObjectName("horizontalLayout_left_124")
        self.label_1241 = QtWidgets.QLabel(self.frame_left_124)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_1241.setFont(font)
        self.label_1241.setObjectName("label_1241")
        self.horizontalLayout_left_124.addWidget(self.label_1241)
        self.lineEdit_1241 = QtWidgets.QLineEdit(self.frame_left_124)
        self.lineEdit_1241.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_1241.setObjectName("lineEdit_1241")
        self.horizontalLayout_left_124.addWidget(self.lineEdit_1241)
        self.label_1242 = QtWidgets.QLabel(self.frame_left_124)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_1242.setFont(font)
        self.label_1242.setObjectName("label_1242")
        self.horizontalLayout_left_124.addWidget(self.label_1242)
        self.lineEdit_1242 = QtWidgets.QLineEdit(self.frame_left_124)
        self.lineEdit_1242.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_1242.setObjectName("lineEdit_1242")
        self.horizontalLayout_left_124.addWidget(self.lineEdit_1242)
        self.label_1243 = QtWidgets.QLabel(self.frame_left_124)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_1243.setFont(font)
        self.label_1243.setObjectName("label_1243")
        self.horizontalLayout_left_124.addWidget(self.label_1243)
        self.verticalLayout_left_12.addWidget(self.frame_left_124)
        self.verticalLayout_scroll_1.addWidget(self.frame_left_12, 0, QtCore.Qt.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(20, 185, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_scroll_1.addItem(spacerItem4)
        self.scrollArea_1.setWidget(self.scrollAreaWidgetContents_1)
        self.verticalLayout_tab_1.addWidget(self.scrollArea_1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_tab_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_tab_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_tab_2.setSpacing(0)
        self.verticalLayout_tab_2.setObjectName("verticalLayout_tab_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_2.setStyleSheet("QScrollArea{\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 390, 445))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_scroll_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_scroll_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_scroll_2.setSpacing(0)
        self.verticalLayout_scroll_2.setObjectName("verticalLayout_scroll_2")
        self.frame_left_21 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_left_21.setMinimumSize(QtCore.QSize(390, 0))
        self.frame_left_21.setMaximumSize(QtCore.QSize(390, 16777215))
        self.frame_left_21.setStyleSheet("#frame_left_21{\n"
"    background: #FFFFFF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"QFrame{\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_left_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_21.setObjectName("frame_left_21")
        self.verticalLayout_left_21 = QtWidgets.QVBoxLayout(self.frame_left_21)
        self.verticalLayout_left_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_left_21.setSpacing(0)
        self.verticalLayout_left_21.setObjectName("verticalLayout_left_21")
        self.frame_left_210 = QtWidgets.QFrame(self.frame_left_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_left_210.sizePolicy().hasHeightForWidth())
        self.frame_left_210.setSizePolicy(sizePolicy)
        self.frame_left_210.setMinimumSize(QtCore.QSize(0, 24))
        self.frame_left_210.setMaximumSize(QtCore.QSize(16777215, 24))
        self.frame_left_210.setStyleSheet("#frame_left_210{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"#frame_210{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}\n"
"QLabel{\n"
"    font-weight: 400;\n"
"    font-size: 12px;\n"
"    color: #303133;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"    background-color: rgb(140, 190, 239);\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(140, 190, 239);\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_left_210.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_210.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_210.setObjectName("frame_left_210")
        self.horizontalLayout_left_210 = QtWidgets.QHBoxLayout(self.frame_left_210)
        self.horizontalLayout_left_210.setContentsMargins(6, 0, 10, 0)
        self.horizontalLayout_left_210.setSpacing(6)
        self.horizontalLayout_left_210.setObjectName("horizontalLayout_left_210")
        self.frame_210 = QtWidgets.QFrame(self.frame_left_210)
        self.frame_210.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_210.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_210.setObjectName("frame_210")
        self.horizontalLayout_210 = QtWidgets.QHBoxLayout(self.frame_210)
        self.horizontalLayout_210.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_210.setSpacing(6)
        self.horizontalLayout_210.setObjectName("horizontalLayout_210")
        self.label_2101 = QtWidgets.QLabel(self.frame_210)
        self.label_2101.setMinimumSize(QtCore.QSize(15, 15))
        self.label_2101.setMaximumSize(QtCore.QSize(15, 15))
        self.label_2101.setText("")
        self.label_2101.setPixmap(QtGui.QPixmap(":/icons/icon_01.png"))
        self.label_2101.setScaledContents(True)
        self.label_2101.setObjectName("label_2101")
        self.horizontalLayout_210.addWidget(self.label_2101)
        self.label_2102 = QtWidgets.QLabel(self.frame_210)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2102.setFont(font)
        self.label_2102.setObjectName("label_2102")
        self.horizontalLayout_210.addWidget(self.label_2102)
        self.horizontalLayout_left_210.addWidget(self.frame_210)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_left_210.addItem(spacerItem5)
        self.pushButton_210 = QtWidgets.QPushButton(self.frame_left_210)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.pushButton_210.setFont(font)
        self.pushButton_210.setText("")
        self.pushButton_210.setIcon(icon1)
        self.pushButton_210.setObjectName("pushButton_210")
        self.horizontalLayout_left_210.addWidget(self.pushButton_210)
        self.verticalLayout_left_21.addWidget(self.frame_left_210)
        self.frame_left_211 = QtWidgets.QFrame(self.frame_left_21)
        self.frame_left_211.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_left_211.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_left_211.setStyleSheet("QLabel{\n"
"    font-weight: 400;\n"
"    font-size: 12px;\n"
"    color: #303133;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}\n"
"QPushButton {\n"
"    height: 20px;\n"
"    background: #00337E;\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgb(0, 83, 200);\n"
"}")
        self.frame_left_211.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_211.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_211.setObjectName("frame_left_211")
        self.horizontalLayout_left_211 = QtWidgets.QHBoxLayout(self.frame_left_211)
        self.horizontalLayout_left_211.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_left_211.setSpacing(6)
        self.horizontalLayout_left_211.setObjectName("horizontalLayout_left_211")
        self.label_211 = QtWidgets.QLabel(self.frame_left_211)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_211.setFont(font)
        self.label_211.setObjectName("label_211")
        self.horizontalLayout_left_211.addWidget(self.label_211)
        self.pushButton_211 = QtWidgets.QPushButton(self.frame_left_211)
        self.pushButton_211.setMinimumSize(QtCore.QSize(108, 20))
        self.pushButton_211.setMaximumSize(QtCore.QSize(108, 20))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_211.setFont(font)
        self.pushButton_211.setStyleSheet("")
        self.pushButton_211.setObjectName("pushButton_211")
        self.horizontalLayout_left_211.addWidget(self.pushButton_211)
        self.verticalLayout_left_21.addWidget(self.frame_left_211)
        self.frame_left_212 = QtWidgets.QFrame(self.frame_left_21)
        self.frame_left_212.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_left_212.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_left_212.setStyleSheet("QPushButton{\n"
"    width: 60px;\n"
"    height: 20px;\n"
"    background: qradialgradient(cx:0%, cy:0%, radius:100%, fx:50%, fy:50%, stop:0 #ECECED, stop:1 #FFFFFF);\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    border: 1px solid #DBDBDD;\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgb(226, 226, 227);\n"
"}\n"
"QLineEdit{\n"
"    width: 309px;\n"
"    height: 20px;\n"
"    background: #ECF3FB;\n"
"    border-radius: 2px 2px 2px 2px;\n"
"    border: 1px solid #DBDBDB;\n"
"}")
        self.frame_left_212.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_212.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_212.setObjectName("frame_left_212")
        self.horizontalLayout_left_212 = QtWidgets.QHBoxLayout(self.frame_left_212)
        self.horizontalLayout_left_212.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_left_212.setSpacing(6)
        self.horizontalLayout_left_212.setObjectName("horizontalLayout_left_212")
        self.lineEdit_212 = QtWidgets.QLineEdit(self.frame_left_212)
        self.lineEdit_212.setObjectName("lineEdit_212")
        self.horizontalLayout_left_212.addWidget(self.lineEdit_212)
        self.pushButton_212 = QtWidgets.QPushButton(self.frame_left_212)
        self.pushButton_212.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_212.setFont(font)
        self.pushButton_212.setObjectName("pushButton_212")
        self.horizontalLayout_left_212.addWidget(self.pushButton_212)
        self.verticalLayout_left_21.addWidget(self.frame_left_212)
        self.frame_left_213 = QtWidgets.QFrame(self.frame_left_21)
        self.frame_left_213.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_left_213.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_left_213.setStyleSheet("QLabel{\n"
"    font-weight: 400;\n"
"    font-size: 12px;\n"
"    color: #303133;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}\n"
"QLineEdit{\n"
"    height: 20px;\n"
"    background: #ECF3FB;\n"
"    border-radius: 2px 2px 2px 2px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"QPushButton{\n"
"    background: #FFFFFF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}\n"
"QRadioButton{\n"
"    font-size: 12px;\n"
"    border: none;\n"
"    background: radial-gradient( #ECECED 0%, #FFFFFF 100%);\n"
"    border-radius: 4px 4px 4px 4px;\n"
"}")
        self.frame_left_213.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_213.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_213.setObjectName("frame_left_213")
        self.horizontalLayout_left_213 = QtWidgets.QHBoxLayout(self.frame_left_213)
        self.horizontalLayout_left_213.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_left_213.setObjectName("horizontalLayout_left_213")
        self.radioButton_213 = QtWidgets.QRadioButton(self.frame_left_213)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        self.radioButton_213.setFont(font)
        self.radioButton_213.setObjectName("radioButton_213")
        self.horizontalLayout_left_213.addWidget(self.radioButton_213)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_left_213.addItem(spacerItem6)
        self.pushButton_213 = QtWidgets.QPushButton(self.frame_left_213)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.pushButton_213.setFont(font)
        self.pushButton_213.setText("")
        self.pushButton_213.setIcon(icon1)
        self.pushButton_213.setObjectName("pushButton_213")
        self.horizontalLayout_left_213.addWidget(self.pushButton_213)
        self.verticalLayout_left_21.addWidget(self.frame_left_213)
        self.frame_left_215 = QtWidgets.QFrame(self.frame_left_21)
        self.frame_left_215.setMinimumSize(QtCore.QSize(0, 240))
        self.frame_left_215.setMaximumSize(QtCore.QSize(16777215, 240))
        self.frame_left_215.setStyleSheet("QTextBrowser{\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: 1px solid #DBDBDB;\n"
"}")
        self.frame_left_215.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_215.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_215.setObjectName("frame_left_215")
        self.verticalLayout_left_215 = QtWidgets.QVBoxLayout(self.frame_left_215)
        self.verticalLayout_left_215.setContentsMargins(10, 6, 10, 6)
        self.verticalLayout_left_215.setObjectName("verticalLayout_left_215")
        self.frame_215 = QtWidgets.QFrame(self.frame_left_215)
        self.frame_215.setStyleSheet("QLabel{\n"
"    font-weight: 400;\n"
"    font-size: 12px;\n"
"    color: #303133;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}\n"
"QPushButton{\n"
"    width: 60px;\n"
"    height: 20px;\n"
"    background: qradialgradient(cx:0%, cy:0%, radius:100%, fx:50%, fy:50%, stop:0 #ECECED, stop:1 #FFFFFF);\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    border: 1px solid #DBDBDD;\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgb(226, 226, 227);\n"
"}")
        self.frame_215.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_215.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_215.setObjectName("frame_215")
        self.horizontalLayout_215 = QtWidgets.QHBoxLayout(self.frame_215)
        self.horizontalLayout_215.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_215.setSpacing(0)
        self.horizontalLayout_215.setObjectName("horizontalLayout_215")
        self.label_215 = QtWidgets.QLabel(self.frame_215)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_215.setFont(font)
        self.label_215.setObjectName("label_215")
        self.horizontalLayout_215.addWidget(self.label_215)
        self.pushButton_215 = QtWidgets.QPushButton(self.frame_215)
        self.pushButton_215.setMinimumSize(QtCore.QSize(60, 0))
        self.pushButton_215.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_215.setFont(font)
        self.pushButton_215.setObjectName("pushButton_215")
        self.horizontalLayout_215.addWidget(self.pushButton_215)
        self.verticalLayout_left_215.addWidget(self.frame_215)
        self.textBrowser_215 = QtWidgets.QTextBrowser(self.frame_left_215)
        self.textBrowser_215.setMinimumSize(QtCore.QSize(0, 200))
        self.textBrowser_215.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.textBrowser_215.setFont(font)
        self.textBrowser_215.setObjectName("textBrowser_215")
        self.verticalLayout_left_215.addWidget(self.textBrowser_215)
        self.verticalLayout_left_21.addWidget(self.frame_left_215)
        self.frame_left_211.raise_()
        self.frame_left_210.raise_()
        self.frame_left_212.raise_()
        self.frame_left_215.raise_()
        self.frame_left_213.raise_()
        self.verticalLayout_scroll_2.addWidget(self.frame_left_21)
        spacerItem7 = QtWidgets.QSpacerItem(20, 121, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_scroll_2.addItem(spacerItem7)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_tab_2.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_tab_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_tab_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_tab_3.setSpacing(0)
        self.verticalLayout_tab_3.setObjectName("verticalLayout_tab_3")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea_3.setStyleSheet("QScrollArea{\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 390, 445))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_scroll_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_scroll_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_scroll_3.setObjectName("verticalLayout_scroll_3")
        self.frame_left_31 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.frame_left_31.setMinimumSize(QtCore.QSize(390, 70))
        self.frame_left_31.setMaximumSize(QtCore.QSize(390, 70))
        self.frame_left_31.setStyleSheet("#frame_left_31{\n"
"    background: #FFFFFF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"QFrame{\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_left_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_31.setObjectName("frame_left_31")
        self.verticalLayout_left_31 = QtWidgets.QVBoxLayout(self.frame_left_31)
        self.verticalLayout_left_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_left_31.setSpacing(0)
        self.verticalLayout_left_31.setObjectName("verticalLayout_left_31")
        self.frame_left_310 = QtWidgets.QFrame(self.frame_left_31)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_left_310.sizePolicy().hasHeightForWidth())
        self.frame_left_310.setSizePolicy(sizePolicy)
        self.frame_left_310.setMinimumSize(QtCore.QSize(0, 24))
        self.frame_left_310.setMaximumSize(QtCore.QSize(16777215, 24))
        self.frame_left_310.setStyleSheet("#frame_left_310{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"#frame_310{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}\n"
"QLabel{\n"
"    font-weight: 400;\n"
"    font-size: 12px;\n"
"    color: #303133;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"    background-color: rgb(140, 190, 239);\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(140, 190, 239);\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_left_310.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_310.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_310.setObjectName("frame_left_310")
        self.horizontalLayout_left_310 = QtWidgets.QHBoxLayout(self.frame_left_310)
        self.horizontalLayout_left_310.setContentsMargins(6, 0, 10, 0)
        self.horizontalLayout_left_310.setSpacing(6)
        self.horizontalLayout_left_310.setObjectName("horizontalLayout_left_310")
        self.frame_310 = QtWidgets.QFrame(self.frame_left_310)
        self.frame_310.setStyleSheet("")
        self.frame_310.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_310.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_310.setObjectName("frame_310")
        self.horizontalLayout_310 = QtWidgets.QHBoxLayout(self.frame_310)
        self.horizontalLayout_310.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_310.setSpacing(6)
        self.horizontalLayout_310.setObjectName("horizontalLayout_310")
        self.label_3101 = QtWidgets.QLabel(self.frame_310)
        self.label_3101.setMinimumSize(QtCore.QSize(15, 15))
        self.label_3101.setMaximumSize(QtCore.QSize(15, 15))
        self.label_3101.setText("")
        self.label_3101.setPixmap(QtGui.QPixmap(":/icons/icon_01.png"))
        self.label_3101.setScaledContents(True)
        self.label_3101.setObjectName("label_3101")
        self.horizontalLayout_310.addWidget(self.label_3101)
        self.label_3102 = QtWidgets.QLabel(self.frame_310)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3102.setFont(font)
        self.label_3102.setObjectName("label_3102")
        self.horizontalLayout_310.addWidget(self.label_3102)
        self.horizontalLayout_left_310.addWidget(self.frame_310)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_left_310.addItem(spacerItem8)
        self.pushButton_310 = QtWidgets.QPushButton(self.frame_left_310)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.pushButton_310.setFont(font)
        self.pushButton_310.setText("")
        self.pushButton_310.setIcon(icon1)
        self.pushButton_310.setObjectName("pushButton_310")
        self.horizontalLayout_left_310.addWidget(self.pushButton_310)
        self.verticalLayout_left_31.addWidget(self.frame_left_310)
        self.frame_left_311 = QtWidgets.QFrame(self.frame_left_31)
        self.frame_left_311.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_left_311.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_left_311.setStyleSheet("QLabel{\n"
"    font-weight: 400;\n"
"    font-size: 12px;\n"
"    color: #303133;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}\n"
"QComboBox{\n"
"    background: radial-gradient( #ECECED 0%, #FFFFFF 100%);\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    border: 1px solid #DBDBDD;\n"
"}\n"
"QLineEdit{\n"
"    height: 20px;\n"
"    background: #ECF3FB;\n"
"    border-radius: 2px 2px 2px 2px;\n"
"    border: 1px solid #DBDBDB;\n"
"}")
        self.frame_left_311.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_311.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_311.setObjectName("frame_left_311")
        self.horizontalLayout_left_311 = QtWidgets.QHBoxLayout(self.frame_left_311)
        self.horizontalLayout_left_311.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_left_311.setObjectName("horizontalLayout_left_311")
        self.comboBox_311 = QtWidgets.QComboBox(self.frame_left_311)
        self.comboBox_311.setMinimumSize(QtCore.QSize(120, 24))
        self.comboBox_311.setMaximumSize(QtCore.QSize(120, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_311.setFont(font)
        self.comboBox_311.setObjectName("comboBox_311")
        self.comboBox_311.addItem("")
        self.comboBox_311.addItem("")
        self.comboBox_311.addItem("")
        self.horizontalLayout_left_311.addWidget(self.comboBox_311)
        self.label_3111 = QtWidgets.QLabel(self.frame_left_311)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3111.setFont(font)
        self.label_3111.setObjectName("label_3111")
        self.horizontalLayout_left_311.addWidget(self.label_3111)
        self.lineEdit_3111 = QtWidgets.QLineEdit(self.frame_left_311)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3111.sizePolicy().hasHeightForWidth())
        self.lineEdit_3111.setSizePolicy(sizePolicy)
        self.lineEdit_3111.setObjectName("lineEdit_3111")
        self.horizontalLayout_left_311.addWidget(self.lineEdit_3111)
        self.label_3112 = QtWidgets.QLabel(self.frame_left_311)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3112.setFont(font)
        self.label_3112.setObjectName("label_3112")
        self.horizontalLayout_left_311.addWidget(self.label_3112)
        self.lineEdit_3112 = QtWidgets.QLineEdit(self.frame_left_311)
        self.lineEdit_3112.setObjectName("lineEdit_3112")
        self.horizontalLayout_left_311.addWidget(self.lineEdit_3112)
        self.verticalLayout_left_31.addWidget(self.frame_left_311)
        self.verticalLayout_scroll_3.addWidget(self.frame_left_31, 0, QtCore.Qt.AlignHCenter)
        self.frame_left_30 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.frame_left_30.setMinimumSize(QtCore.QSize(390, 0))
        self.frame_left_30.setMaximumSize(QtCore.QSize(390, 16777215))
        self.frame_left_30.setStyleSheet("#frame_left_30{\n"
"    background: #FFFFFF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"QFrame{\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_left_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_30.setObjectName("frame_left_30")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_left_30)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_left_300 = QtWidgets.QFrame(self.frame_left_30)
        self.frame_left_300.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_left_300.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_left_300.setStyleSheet("#frame_left_300{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"#frame_3001{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: none;\n"
"}\n"
"QLabel{\n"
"    font-weight: 400;\n"
"    font-size: 12px;\n"
"    color: #303133;\n"
"    text-align: left;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"    background: radial-gradient( #ECECED 0%, #FFFFFF 100%);\n"
"    border-radius: 4px 4px 4px 4px;\n"
"}\n"
"QTextBrowser{\n"
"    background: radial-gradient( #ECECED 0%, #FFFFFF 100%);\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"QPushButton{\n"
"    width: 60px;\n"
"    height: 20px;\n"
"    background: qradialgradient(cx:0%, cy:0%, radius:100%, fx:50%, fy:50%, stop:0 #ECECED, stop:1 #FFFFFF);\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    border: 1px solid #DBDBDD;\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgb(226, 226, 227);\n"
"}")
        self.frame_left_300.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_300.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_300.setObjectName("frame_left_300")
        self.horizontalLayout_left_300 = QtWidgets.QHBoxLayout(self.frame_left_300)
        self.horizontalLayout_left_300.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_left_300.setObjectName("horizontalLayout_left_300")
        self.label_300 = QtWidgets.QLabel(self.frame_left_300)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_300.setFont(font)
        self.label_300.setObjectName("label_300")
        self.horizontalLayout_left_300.addWidget(self.label_300)
        self.frame_3001 = QtWidgets.QFrame(self.frame_left_300)
        self.frame_3001.setMinimumSize(QtCore.QSize(120, 24))
        self.frame_3001.setMaximumSize(QtCore.QSize(120, 24))
        self.frame_3001.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3001.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3001.setObjectName("frame_3001")
        self.horizontalLayout_3001 = QtWidgets.QHBoxLayout(self.frame_3001)
        self.horizontalLayout_3001.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3001.setObjectName("horizontalLayout_3001")
        self.label_3001 = QtWidgets.QLabel(self.frame_3001)
        self.label_3001.setMinimumSize(QtCore.QSize(80, 0))
        self.label_3001.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3001.setFont(font)
        self.label_3001.setObjectName("label_3001")
        self.horizontalLayout_3001.addWidget(self.label_3001)
        self.textBrowser_3001 = QtWidgets.QTextBrowser(self.frame_3001)
        self.textBrowser_3001.setMinimumSize(QtCore.QSize(40, 0))
        self.textBrowser_3001.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser_3001.setFont(font)
        self.textBrowser_3001.setObjectName("textBrowser_3001")
        self.horizontalLayout_3001.addWidget(self.textBrowser_3001)
        self.horizontalLayout_left_300.addWidget(self.frame_3001)
        self.pushButton_300 = QtWidgets.QPushButton(self.frame_left_300)
        self.pushButton_300.setMinimumSize(QtCore.QSize(60, 0))
        self.pushButton_300.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_300.setFont(font)
        self.pushButton_300.setObjectName("pushButton_300")
        self.horizontalLayout_left_300.addWidget(self.pushButton_300)
        self.verticalLayout_2.addWidget(self.frame_left_300)
        self.textBrowser_300 = QtWidgets.QTextBrowser(self.frame_left_30)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_300.sizePolicy().hasHeightForWidth())
        self.textBrowser_300.setSizePolicy(sizePolicy)
        self.textBrowser_300.setMinimumSize(QtCore.QSize(380, 0))
        self.textBrowser_300.setStyleSheet("QTextBrowser {\n"
"    background: #FAFBFE;\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: 1px solid #DBDBDB;\n"
"}")
        self.textBrowser_300.setObjectName("textBrowser_300")
        self.verticalLayout_2.addWidget(self.textBrowser_300)
        self.verticalLayout_scroll_3.addWidget(self.frame_left_30, 0, QtCore.Qt.AlignHCenter)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_tab_3.addWidget(self.scrollArea_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_7.addWidget(self.tabWidget)
        self.horizontalLayout_up.addWidget(self.frame_left)
        self.frame_right = QtWidgets.QFrame(self.frame_up)
        self.frame_right.setStyleSheet("#frame_right{\n"
"    border: none;\n"
"}\n"
"#frame_view{\n"
"    background: radial-gradient( #E3EFFC 0%, #CDDEFF 100%);\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: 1px solid #DBDBDB;\n"
"}")
        self.frame_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_right.setObjectName("frame_right")
        self.verticalLayout_right = QtWidgets.QVBoxLayout(self.frame_right)
        self.verticalLayout_right.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_right.setSpacing(6)
        self.verticalLayout_right.setObjectName("verticalLayout_right")
        self.frame_view = QtWidgets.QFrame(self.frame_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_view.sizePolicy().hasHeightForWidth())
        self.frame_view.setSizePolicy(sizePolicy)
        self.frame_view.setStyleSheet("#frame_graph{\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: none;\n"
"}\n"
"#frame_view_set{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 0px 0px;\n"
"    border: 1px solid #DBDBDB;\n"
"}")
        self.frame_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_view.setObjectName("frame_view")
        self.verticalLayout_view = QtWidgets.QVBoxLayout(self.frame_view)
        self.verticalLayout_view.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_view.setSpacing(0)
        self.verticalLayout_view.setObjectName("verticalLayout_view")
        self.frame_view_set = QtWidgets.QFrame(self.frame_view)
        self.frame_view_set.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_view_set.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_view_set.setStyleSheet("#frame_view_set_1{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 5px 5px;\n"
"}\n"
"#frame_view_set_2{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 5px 5px\n"
"}")
        self.frame_view_set.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_view_set.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_view_set.setObjectName("frame_view_set")
        self.verticalLayout_view_set = QtWidgets.QVBoxLayout(self.frame_view_set)
        self.verticalLayout_view_set.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_view_set.setSpacing(0)
        self.verticalLayout_view_set.setObjectName("verticalLayout_view_set")
        self.frame_view_set_1 = QtWidgets.QFrame(self.frame_view_set)
        self.frame_view_set_1.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_view_set_1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_view_set_1.setStyleSheet("#frame_view_xyz{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: none;\n"
"}\n"
"QComboBox{\n"
"    background: radial-gradient( #ECECED 0%, #FFFFFF 100%);\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    border: 1px solid #DBDBDD;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(140, 190, 239);\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: none;\n"
"}")
        self.frame_view_set_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_view_set_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_view_set_1.setObjectName("frame_view_set_1")
        self.horizontalLayout_view_set_1 = QtWidgets.QHBoxLayout(self.frame_view_set_1)
        self.horizontalLayout_view_set_1.setContentsMargins(6, 0, 6, 0)
        self.horizontalLayout_view_set_1.setSpacing(6)
        self.horizontalLayout_view_set_1.setObjectName("horizontalLayout_view_set_1")
        self.comboBox = QtWidgets.QComboBox(self.frame_view_set_1)
        self.comboBox.setMinimumSize(QtCore.QSize(120, 24))
        self.comboBox.setMaximumSize(QtCore.QSize(120, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_view_set_1.addWidget(self.comboBox)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_view_set_1.addItem(spacerItem9)
        self.frame_view_xyz = QtWidgets.QFrame(self.frame_view_set_1)
        self.frame_view_xyz.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255)\n"
"}")
        self.frame_view_xyz.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_view_xyz.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_view_xyz.setObjectName("frame_view_xyz")
        self.horizontalLayout_view_xyz = QtWidgets.QHBoxLayout(self.frame_view_xyz)
        self.horizontalLayout_view_xyz.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_view_xyz.setSpacing(2)
        self.horizontalLayout_view_xyz.setObjectName("horizontalLayout_view_xyz")
        self.pushButton_xy = QtWidgets.QPushButton(self.frame_view_xyz)
        self.pushButton_xy.setMaximumSize(QtCore.QSize(16777215, 24))
        self.pushButton_xy.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icon_xy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_xy.setIcon(icon2)
        self.pushButton_xy.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_xy.setObjectName("pushButton_xy")
        self.horizontalLayout_view_xyz.addWidget(self.pushButton_xy)
        self.pushButton_yx = QtWidgets.QPushButton(self.frame_view_xyz)
        self.pushButton_yx.setMaximumSize(QtCore.QSize(16777215, 24))
        self.pushButton_yx.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icon_yx.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_yx.setIcon(icon3)
        self.pushButton_yx.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_yx.setObjectName("pushButton_yx")
        self.horizontalLayout_view_xyz.addWidget(self.pushButton_yx)
        self.pushButton_yz = QtWidgets.QPushButton(self.frame_view_xyz)
        self.pushButton_yz.setMaximumSize(QtCore.QSize(16777215, 24))
        self.pushButton_yz.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icon_yz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_yz.setIcon(icon4)
        self.pushButton_yz.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_yz.setObjectName("pushButton_yz")
        self.horizontalLayout_view_xyz.addWidget(self.pushButton_yz)
        self.pushButton_zy = QtWidgets.QPushButton(self.frame_view_xyz)
        self.pushButton_zy.setMaximumSize(QtCore.QSize(16777215, 24))
        self.pushButton_zy.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icon_zy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_zy.setIcon(icon5)
        self.pushButton_zy.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_zy.setObjectName("pushButton_zy")
        self.horizontalLayout_view_xyz.addWidget(self.pushButton_zy)
        self.pushButton_zx = QtWidgets.QPushButton(self.frame_view_xyz)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_zx.sizePolicy().hasHeightForWidth())
        self.pushButton_zx.setSizePolicy(sizePolicy)
        self.pushButton_zx.setMaximumSize(QtCore.QSize(16777215, 24))
        self.pushButton_zx.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icon_zx.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_zx.setIcon(icon6)
        self.pushButton_zx.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_zx.setObjectName("pushButton_zx")
        self.horizontalLayout_view_xyz.addWidget(self.pushButton_zx)
        self.pushButton_xz = QtWidgets.QPushButton(self.frame_view_xyz)
        self.pushButton_xz.setMaximumSize(QtCore.QSize(16777215, 24))
        self.pushButton_xz.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icon_xz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_xz.setIcon(icon7)
        self.pushButton_xz.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_xz.setObjectName("pushButton_xz")
        self.horizontalLayout_view_xyz.addWidget(self.pushButton_xz)
        self.horizontalLayout_view_set_1.addWidget(self.frame_view_xyz)
        self.verticalLayout_view_set.addWidget(self.frame_view_set_1)
        self.frame_view_set_2 = QtWidgets.QFrame(self.frame_view_set)
        self.frame_view_set_2.setStyleSheet("#frame_view_present{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: none;\n"
"}\n"
"#frame_view_time{\n"
"    background: radial-gradient, #8CBEEF;\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: none;\n"
"}\n"
"QLabel{\n"
"    background: radial-gradient( #ECECED 0%, #FFFFFF 100%);\n"
"    border-radius: 4px 4px 4px 4px;\n"
"}\n"
"QTextBrowser{\n"
"    background: radial-gradient( #ECECED 0%, #FFFFFF 100%);\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    border: 1px solid #DBDBDB;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(140, 190, 239);\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: none;\n"
"}\n"
"QToolButton{\n"
"    background-color: rgb(140, 190, 239);\n"
"    border-radius: 5px 5px 5px 5px;\n"
"    border: none;\n"
"}")
        self.frame_view_set_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_view_set_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_view_set_2.setObjectName("frame_view_set_2")
        self.horizontalLayout_view_set_2 = QtWidgets.QHBoxLayout(self.frame_view_set_2)
        self.horizontalLayout_view_set_2.setContentsMargins(6, 0, 6, 0)
        self.horizontalLayout_view_set_2.setObjectName("horizontalLayout_view_set_2")
        self.frame_view_present = QtWidgets.QFrame(self.frame_view_set_2)
        self.frame_view_present.setMinimumSize(QtCore.QSize(120, 24))
        self.frame_view_present.setMaximumSize(QtCore.QSize(120, 24))
        self.frame_view_present.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_view_present.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_view_present.setObjectName("frame_view_present")
        self.horizontalLayout_view_present = QtWidgets.QHBoxLayout(self.frame_view_present)
        self.horizontalLayout_view_present.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_view_present.setObjectName("horizontalLayout_view_present")
        self.label_2 = QtWidgets.QLabel(self.frame_view_present)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_view_present.addWidget(self.label_2)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_view_present)
        self.textBrowser_2.setMinimumSize(QtCore.QSize(40, 0))
        self.textBrowser_2.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.horizontalLayout_view_present.addWidget(self.textBrowser_2)
        self.horizontalLayout_view_set_2.addWidget(self.frame_view_present)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_view_set_2.addItem(spacerItem10)
        self.frame_view_time = QtWidgets.QFrame(self.frame_view_set_2)
        self.frame_view_time.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255)\n"
"}\n"
"QToolButton{\n"
"    background-color: rgb(255, 255, 255)\n"
"}")
        self.frame_view_time.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_view_time.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_view_time.setObjectName("frame_view_time")
        self.horizontalLayout_view_time = QtWidgets.QHBoxLayout(self.frame_view_time)
        self.horizontalLayout_view_time.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_view_time.setSpacing(2)
        self.horizontalLayout_view_time.setObjectName("horizontalLayout_view_time")
        self.pushButton_first = QtWidgets.QPushButton(self.frame_view_time)
        self.pushButton_first.setMaximumSize(QtCore.QSize(16777215, 24))
        self.pushButton_first.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icon_first.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_first.setIcon(icon8)
        self.pushButton_first.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_first.setObjectName("pushButton_first")
        self.horizontalLayout_view_time.addWidget(self.pushButton_first)
        self.pushButton_previous = QtWidgets.QPushButton(self.frame_view_time)
        self.pushButton_previous.setMaximumSize(QtCore.QSize(16777215, 24))
        self.pushButton_previous.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icon_previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_previous.setIcon(icon9)
        self.pushButton_previous.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_previous.setObjectName("pushButton_previous")
        self.horizontalLayout_view_time.addWidget(self.pushButton_previous)
        self.pushButton_run = QtWidgets.QToolButton(self.frame_view_time)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_run.sizePolicy().hasHeightForWidth())
        self.pushButton_run.setSizePolicy(sizePolicy)
        self.pushButton_run.setMaximumSize(QtCore.QSize(16777215, 24))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icon_run.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon10.addPixmap(QtGui.QPixmap(":/icons/icon_stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_run.setIcon(icon10)
        self.pushButton_run.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_run.setCheckable(True)
        self.pushButton_run.setChecked(False)
        self.pushButton_run.setObjectName("pushButton_run")
        self.horizontalLayout_view_time.addWidget(self.pushButton_run)
        self.pushButton_next = QtWidgets.QPushButton(self.frame_view_time)
        self.pushButton_next.setMaximumSize(QtCore.QSize(16777215, 24))
        self.pushButton_next.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icon_next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next.setIcon(icon11)
        self.pushButton_next.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_next.setObjectName("pushButton_next")
        self.horizontalLayout_view_time.addWidget(self.pushButton_next)
        self.pushButton_last = QtWidgets.QPushButton(self.frame_view_time)
        self.pushButton_last.setMaximumSize(QtCore.QSize(16777215, 24))
        self.pushButton_last.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icon_last.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_last.setIcon(icon12)
        self.pushButton_last.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_last.setObjectName("pushButton_last")
        self.horizontalLayout_view_time.addWidget(self.pushButton_last)
        self.horizontalLayout_view_set_2.addWidget(self.frame_view_time)
        self.verticalLayout_view_set.addWidget(self.frame_view_set_2)
        self.verticalLayout_view.addWidget(self.frame_view_set)
        self.frame_graph = QtWidgets.QFrame(self.frame_view)
        self.frame_graph.setMinimumSize(QtCore.QSize(0, 480))
        self.frame_graph.setMaximumSize(QtCore.QSize(16777215, 480))
        self.frame_graph.setStyleSheet("")
        self.frame_graph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph.setObjectName("frame_graph")
        self.verticalLayout_view.addWidget(self.frame_graph)
        self.verticalLayout_right.addWidget(self.frame_view)
        self.horizontalLayout_up.addWidget(self.frame_right, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.frame_up)
        self.frame_down = QtWidgets.QFrame(Dialog)
        self.frame_down.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_down.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_down.setStyleSheet("QPushButton{\n"
"    width: 56px;\n"
"    height: 24px;\n"
"    background: #FFFFFF;\n"
"    border-radius: 4px 4px 4px 4px;\n"
"    border: 1px solid #00337E;\n"
"    font-weight: 600;\n"
"    font-size: 12px;\n"
"    color: #00337E;\n"
"    font-style: normal;\n"
"    text-transform: none;\n"
"}")
        self.frame_down.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_down.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_down.setObjectName("frame_down")
        self.horizontalLayout_down = QtWidgets.QHBoxLayout(self.frame_down)
        self.horizontalLayout_down.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_down.setSpacing(0)
        self.horizontalLayout_down.setObjectName("horizontalLayout_down")
        self.pushButton_0 = QtWidgets.QPushButton(self.frame_down)
        self.pushButton_0.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setObjectName("pushButton_0")
        self.horizontalLayout_down.addWidget(self.pushButton_0)
        self.verticalLayout.addWidget(self.frame_down)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "管道流体速度压强温度展示"))
        self.label_1102.setText(_translate("Dialog", "导入油箱"))
        self.label_1111.setText(_translate("Dialog", "读取油箱几何模型："))
        self.label_1112.setText(_translate("Dialog", "文件单位："))
        self.comboBox_111.setItemText(0, _translate("Dialog", "m"))
        self.comboBox_111.setItemText(1, _translate("Dialog", "mm"))
        self.pushButton_111.setText(_translate("Dialog", "选择文件 (.stl)"))
        self.pushButton_112.setText(_translate("Dialog", "读取"))
        self.radioButton_113.setText(_translate("Dialog", "显示油箱"))
        self.label_1202.setText(_translate("Dialog", "导入管路"))
        self.label_121.setText(_translate("Dialog", "读取管路几何模型："))
        self.pushButton_121.setText(_translate("Dialog", "选择文件夹"))
        self.pushButton_122.setText(_translate("Dialog", "读取"))
        self.label_1231.setText(_translate("Dialog", "关节坐标文件名："))
        self.label_1232.setText(_translate("Dialog", "关节边长："))
        self.label_1233.setText(_translate("Dialog", "mm"))
        self.label_1241.setText(_translate("Dialog", "管道连接文件名："))
        self.label_1242.setText(_translate("Dialog", "管道半径："))
        self.label_1243.setText(_translate("Dialog", "mm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Dialog", "模型"))
        self.label_2102.setText(_translate("Dialog", "导入数据"))
        self.label_211.setText(_translate("Dialog", "读取文件夹（多时间步）："))
        self.pushButton_211.setText(_translate("Dialog", "选择文件夹"))
        self.pushButton_212.setText(_translate("Dialog", "读取"))
        self.radioButton_213.setText(_translate("Dialog", "自动监测新增文件"))
        self.label_215.setText(_translate("Dialog", "已读取的文件信息："))
        self.pushButton_215.setText(_translate("Dialog", "清空"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "数据"))
        self.label_3102.setText(_translate("Dialog", "设置监控范围"))
        self.comboBox_311.setItemText(0, _translate("Dialog", "速度 (mm/s)"))
        self.comboBox_311.setItemText(1, _translate("Dialog", "压强 (Pa)"))
        self.comboBox_311.setItemText(2, _translate("Dialog", "温度 (K)"))
        self.label_3111.setText(_translate("Dialog", "min："))
        self.label_3112.setText(_translate("Dialog", "max："))
        self.label_300.setText(_translate("Dialog", "不在有效范围数据："))
        self.label_3001.setText(_translate("Dialog", "当前时间步:"))
        self.pushButton_300.setText(_translate("Dialog", "清空"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "监控"))
        self.comboBox.setItemText(0, _translate("Dialog", "速度"))
        self.comboBox.setItemText(1, _translate("Dialog", "压强"))
        self.comboBox.setItemText(2, _translate("Dialog", "温度"))
        self.label_2.setText(_translate("Dialog", "当前时间步:"))
        self.pushButton_run.setText(_translate("Dialog", "..."))
        self.pushButton_0.setText(_translate("Dialog", "返回"))
import res_rc
